services:
    postgres:
        image: postgres
        restart: always
        volumes:
            - /data/postgres:/data/postgres
        ports:
            - '5432:5432'
        networks:
            - postgres
        env_file:
            - docker.env

    api:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
            - /app/node_modules
        env_file:
            - .env
        ports:
            - '3000:3000'
        depends_on:
            - postgres
        networks:
            - postgres

networks:
    postgres:
        driver: bridge
